### PR TITLE
current changes

### PR DESCRIPTION
**Pull request by ChrisRusu1**
change launch file for max current

### CODE REVIEW

**Comment by ChrisRusu1** [comment]
@ConnorNeed it should just work, but dont want to merge to main without testing first. If you dont mind checking tomorrow when out at the beach, bring a current sensor or something and double check that it actually changes the max. Thanks

**Review by ConnorNeed — COMMENTED** [review]
LG2M. I will merge it after we confirm it is working tomorrow night

**Comment by noodlekid** [comment]
Could we get a status update on this MR, would be nice to close it out?

**Comment by noodlekid** [comment]
Closing PR due to stale changes.

**Pull request closed without merging**
